server:
  port: 8001
  servlet:
    context-path: /boot-test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-wait: -1ms
          max-active: 16

logging:
  level:
    com.ya.boottest :  DEBUG
    root: INFO


mybatis-plus:
  mapper-locations: classpath*:com/ya/boottest/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: false
  pageSizeZero: false
  defaultCount: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '1.default'
      display-name: '默认'
      paths-to-match: '/**'
      packages-to-scan: com.ya.boottest
    - group: '2.common'
      display-name: '公共'
      paths-to-match: '/common/**'
      packages-to-scan: com.ya.boottest
    - group: '3.goods'
      display-name: '商品'
      paths-to-match: '/goods/**'
      packages-to-scan: com.ya.boottest

knife4j:
  enable: true
  setting:
    language: zh_cn

ya-app:
  auth:
    jwt:
      secret: aBcD1234eFgH5678IjKl90MnOpQrStUvWxYz4567
      expiration: 1800
      not-before: 2024-01-01
